version: '2'
services:
  mltools-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/mlTools/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mlTools
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
